#! /bin/bash

# alias l='ls -Glat'
alias l='ls -hltr --color=always'
alias la='ls -hAltr --color=always'
# alias ll='ls -GAhltr'
alias ll='ls -Ghaltr'

# editors
alias vi='nvim'
alias e='emacsclient -t'
alias ec='emacsclient -c'
alias et='emacsclient -t'
alias emacs-deamon="emacs --daemon"
alias emacs-kill="emacsclient -e '(kill-emacs)'"
alias emacs-restart="emacsclient -e '(restart-emacs)'"

# grep
alias grep='grep --color=auto'
alias grepf='grep -Rin --color=auto --exclude-dir={node_modules,.git,dist,.next,build}'
alias grepl='grep -Rinl --color=auto --exclude-dir={node_modules,.git,dist,.next,build}'

# nkf
alias url_decode='nkf -w --url-input'

#alias diff= 'diff --color=always '
alias diffy='diff --color=always --suppress-common-line -y'
alias diffu='diff --color=always -u'

# fzf
alias fzf='fzf --preview "bat --color=always --style=numbers --line-range :500 {}"'
alias vif='vi $(fzf)'

# macOS
alias clip='pbcopy'

# Git
alias g='git'

alias gs='git status'
alias gsw='git show'
alias ga='git add'
alias gc='git commit'
alias gch='git checkout'
alias gd='git diff'
alias gb='git branch'
alias gw='git switch'
alias gl='git log --graph'
alias gt='git tag'
alias gf='git fetch'

alias push='git push'
alias pull='git pull'
alias clone='git clone'

# npm
alias nr='npm run'
alias nt='npm run test'
alias dev='npm run dev'

