#! /bin/bash

CUR=$(dirname ${0} | sed 's/\/.+$//')

# setopt emacs
setopt vi

# ビープ音を鳴らさない
setopt no_beep

# cd 省略
setopt autocd

# ターミナル間でhistoryを共有する
# setopt share_history

# zshでもコメントを使えるようにする
setopt interactivecomments

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

# aliases
[[ -f $CUR/aliases ]] && source $CUR/aliases

# functions
[[ -f $CUR/functions ]] && source $CUR/functions
