#! /bin/bash

# aliases
alias vi='nvim'

# alias l='ls -Glat'
alias l='ls -hlt --color=always | head -n 20'
alias la='ls -hAlt --color=always | head -n 20'

# alias ll='ls -GAhltr'
alias ll='ls -Ghalt'

alias grep='grep -n --color=auto'
alias grepf='grep -Rin --color=auto --exclude-dir={node_modules,.git,dist,.next,build}'
alias grepl='grep -Rinl --color=auto --exclude-dir={node_modules,.git,dist,.next,build}'

# nkf
alias url_decode='nkf -w --url-input'

#alias diff= 'diff --color=always '
alias diffy='diff --color=always --suppress-common-line -y'
alias diffu='diff --color=always -u'

# macOS
alias clip='pbcopy'

# Git
alias g='git'

alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gm='git commit'
alias gd='git diff'
alias gf='git diff'
alias gb='git branch'
alias gw='git switch'
alias gl='git log --graph'
alias gt='git tag'
alias gf='git fetch'

alias push='git push'
alias pull='git pull'
alias fetch='git fetch'
alias clone='git clone'
alias show='git show'

# npm
alias nr='npm run'
alias nt='npm run test'
alias nd='npm run dev'
alias dev='npm run dev'

